### ISSUE TITLE
Compiler notes

### ISSUE THREAD

**Issue by jehuamanna** [AnanyaTripathy/365-Days-Of-Code#2]
Using which source reference did you compile it? It's very useful. I am reading them. Please let me know the book/video reference too.

**Comment by AnanyaTripathy** [comment]
Er. Chinmayee Rout . She provided some of these notes while teaching in class. And the rest are from NPTEL website. NPTEL website has really great faculties.

**Comment by jehuamanna** [comment]
Thanks
